# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MyData

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Data(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsData(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Data()
        x.Init(buf, n + offset)
        return x

    # Data
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Data
    def M(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MyData.Image import Image
            obj = Image()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Data
    def MLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Data
    def MIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DataStart(builder): builder.StartObject(1)
def DataAddM(builder, M): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(M), 0)
def DataStartMVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def DataEnd(builder): return builder.EndObject()
